[build]
  base = ""
  publish = "build"
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyD-_CColzyihNeqiPGSacdBaRuIheYKEcg"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "dj-requests-app.firebaseapp.com"
  REACT_APP_FIREBASE_DATABASE_URL = "https://dj-requests-app-default-rtdb.firebaseio.com"
  REACT_APP_FIREBASE_PROJECT_ID = "dj-requests-app"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "dj-requests-app.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "154223856069"
  REACT_APP_FIREBASE_APP_ID = "1:154223856069:web:82fc7c3b3f21acc9eda3ac"
